### ISSUE TITLE
Popular projects on main page differs to when clicked on

### ISSUE THREAD

**Issue by exerro** [Xella37/PineStore-site#5]
On the main page:
![image](https://github.com/Xella37/PineStore-site/assets/2530315/cfc5c08f-af04-45d6-998a-76ee1dd8422d)

After clicking "Most popular >":
![image](https://github.com/Xella37/PineStore-site/assets/2530315/588883d7-73b1-4789-bfa1-ef08e604fc8c)

It's super important that the order of projects here are identical!

In all seriousness it is a bit weird how they change - makes it not entirely clear what it's showing and might be indicative of a bug somewhere.

As an aside, I'd expect some visual indicator (like a download count) to be descending in a list like that. If popularity isn't measured by downloads, what's it measured by?

**Comment by Xella37** [comment]
Hm I understand that they should be the same, but as far as I can see, they should be sorted in the same way based on `project.downloads_recent`, just on the homepage it then takes the first 6 items.

Will need to figure out what causes the differences, but it looks like it happens when there is a tie. We could just have it check the total downloads and publish date after if there is a tie. That would help with the inconsistency.

**Comment by Xella37** [comment]
This has been changed with fd68a851cdfa963a9efe972d4781221d4efe2e6e and they now have the same order :)
